In [4]:
# Day 1 AM Lab 1
import numpy as np

# this returns a number whose probability of occurence is p
def sampleValue (p):
        return np.flatnonzero (np.random.multinomial (1, p, 1))[0]

# there are 2000 words in the corpus
alpha = np.full (2000, .1)

# there are 100 topics
beta = np.full (100, .1)

# this gets us the probabilty of each word happening in each of the 100 topics
wordsInTopic = np.random.dirichlet (alpha, 100)
# wordsInCorpus[i] will give us the number of each word in the document
wordsInCorpus = {}

# generate each doc
for doc in range (0, 50):
        #
        # no words in this doc yet
        wordsInDoc = {}
        #
        # get the topic probabilities for this doc
        topicsInDoc = np.random.dirichlet (beta)
        #
        # generate each of the 1000 words in this document
        for word in range (0, 1000):
                #
                # select the topic and the word
                whichTopic = sampleValue (topicsInDoc)
                whichWord = sampleValue (wordsInTopic[whichTopic])
                #
                # and record the word
                wordsInDoc [whichWord] = wordsInDoc.get (whichWord, 0) + 1
                #
        # now, remember this document
        wordsInCorpus [doc] = wordsInDoc
print(wordsInCorpus [doc])
print(type(wordsInCorpus [doc]))
print(wordsInCorpus[4])

{948: 1, 4: 1, 314: 1, 759: 2, 940: 6, 662: 2, 403: 4, 1158: 1, 1133: 3, 235: 2, 833: 3, 275: 2, 149: 4, 1519: 1, 780: 3, 1450: 3, 1571: 2, 608: 1, 1846: 2, 792: 4, 1674: 1, 1948: 2, 1712: 1, 186: 3, 1270: 2, 1076: 1, 1328: 2, 103: 1, 1645: 1, 460: 1, 747: 4, 336: 5, 546: 3, 622: 1, 1324: 6, 1982: 3, 951: 1, 1575: 2, 173: 1, 63: 1, 632: 1, 1344: 1, 1247: 2, 389: 1, 492: 1, 797: 3, 1026: 2, 495: 1, 16: 1, 1492: 2, 713: 2, 1719: 3, 847: 2, 771: 1, 1877: 1, 1109: 1, 328: 3, 1940: 4, 1318: 2, 938: 1, 1642: 3, 738: 2, 1280: 2, 1548: 1, 412: 3, 763: 2, 48: 1, 1303: 1, 536: 1, 520: 2, 534: 1, 1668: 2, 402: 4, 376: 2, 198: 1, 1618: 1, 1847: 5, 1339: 4, 6: 1, 1395: 1, 1099: 3, 84: 2, 1741: 1, 130: 1, 372: 1, 92: 3, 486: 1, 1515: 4, 1470: 1, 592: 2, 1915: 4, 1034: 4, 1430: 2, 1894: 1, 979: 2, 1841: 3, 724: 2, 1513: 4, 392: 1, 609: 2, 382: 2, 1068: 2, 497: 1, 1934: 2, 1021: 7, 465: 1, 1496: 6, 627: 1, 1072: 1, 1458: 1, 1912: 1, 1156: 2, 1404: 3, 1511: 1, 1279: 2, 1985: 1, 1202: 1, 697: 2, 825: 2,

In [10]:
# Day 1 AM Lab 2
import numpy as np

# there are 2000 words in the corpus
alpha = np.full (2000, .1)

# there are 100 topics
beta = np.full (100, .1)

# this gets us the probabilty of each word happening in each of the 100 topics
wordsInTopic = np.random.dirichlet (alpha, 100)

# wordsInCorpus[i] will give us the vector of words in document i
wordsInCorpus = np.zeros ((50, 2000))

# generate each doc
for doc in range (0, 50):
        #
        # get the topic probabilities for this doc
        topicsInDoc = np.random.dirichlet (beta)
        #
        # assign each of the 1000 words in this doc to a topic
        wordsToTopic = np.random.multinomial (1000, topicsInDoc)
        #
        # and generate each of the 1000 words
        for topic in range (0, 100):
                wordsFromCurrentTopic = np.random.multinomial (wordsToTopic[topic], wordsInTopic[topic])
                wordsInCorpus[doc] = np.add (wordsInCorpus[doc], wordsFromCurrentTopic)
print(wordsInCorpus [doc])
print(type(wordsInCorpus [doc]))
print(wordsInCorpus[2,1:10])

[2. 0. 0. ... 0. 2. 0.]
<class 'numpy.ndarray'>
[1. 1. 0. 0. 0. 0. 0. 1. 0.]


In [13]:
# Day 1 AM Lab 2 - alternate code by teacher
import numpy as np

# there are 2000 words in the corpus
alpha = np.full (2000, .1)

# there are 100 topics
beta = np.full (100, .1)

# this gets us the probabilty of each word happening in each of the 100 topics
wordsInTopic = np.random.dirichlet (alpha, 100)

# wordsInCorpus[i] will give us the vector of words in document i
wordsInCorpus = np.zeros ((50, 2000))

# generate each doc
for doc in range (0, 50):
        #
        # get the topic probabilities for this doc
        topicsInDoc = np.random.dirichlet (beta)
        #
        # assign each of the 1000 words in this doc to a topic
        wordsFromCurrentTopic = wordsToTopic[topic]
        #
        # and generate each of the 1000 words
        for topic in range (0, 100):
                wordsFromCurrentTopic = wordsToTopic[topic]
                wordsInCorpus[doc] = np.add (wordsInCorpus[doc], np.random.multinomial (wordsToTopic[topic], wordsInTopic[topic]))
print(wordsInCorpus [doc])
print(type(wordsInCorpus [doc]))
print(wordsInCorpus[2,1:10])

[0. 0. 0. ... 1. 0. 0.]
<class 'numpy.ndarray'>
[1. 0. 1. 0. 3. 1. 1. 0. 0.]


In [11]:
np.zeros ((50, 2000))

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [ ]:
# Day 1 AM Lab 3
import numpy as np
# there are 2000 words in the corpus
alpha = np.full (2000, .1)

# there are 100 topics
beta = np.full (100, .1)

# this gets us the probabilty of each word happening in each of the 100 topics
wordsInTopic = np.random.dirichlet (alpha, 100)

# produced [doc, topic, word] gives us the number of times that the given word was
# produced by the given topic in the given doc
produced = np.zeros ((50, 100, 2000))

# generate each doc
for doc in range (0, 50):
        #
        # get the topic probabilities for this doc
        topicsInDoc = np.random.dirichlet (beta)
        #
        # assign each of the 1000 words in this doc to a topic
        wordsToTopic = np.random.multinomial (1000, topicsInDoc)
        #
        # and generate each of the 1000 words
        for topic in range (0, 100):
                produced[doc, topic] = np.random.multinomial (wordsToTopic[topic], wordsInTopic[topic])

#

In [15]:
# 1 Write a line of code that computes the number of words produced by topic 17 in document 18.
produced[18,17,:].sum () # or produced[18,17].sum ()

0.0

In [16]:
# 1 Write a line of code that computes the number of words produced by topic 17 in document 18.
produced[18,17].sum ()

0.0

In [20]:
# 2 Write a line of code that computes the number of words produced by topic 17 thru 45 in document 18.
produced[18,17:46].sum ()

668.0

In [22]:
# 3 Write a line of code that computes the number of words in the entire corpus. = 50 docs * 1000 words to topic
produced.sum () # or produced[:,:,:].sum ()


50000.0

In [23]:
# 4 Write a line of code that computes the number of words in the entire corpus produced by topic 17 .
produced[:,17,:].sum () # or produced[:,17].sum ()

204.0

In [24]:
# 4 Write a line of code that computes the number of words in the entire corpus produced by topic 17 .
produced[:,17].sum ()

204.0

In [25]:
# 5 Write a line of code that computes the number of words in the entire corpus produced by topic 17 or topic 23.
produced[:,np.array([17,23]),:].sum ()

598.0

In [46]:
# 5 Write a line of code that computes the number of words in the entire corpus produced by topic 17 or topic 23.  
#  NOT correct version uses addition 
produced[:,17].sum () + produced[:,23].sum ()

598.0

In [47]:
# 6 Write a line of code that computes the number of words in the entire corpus produced by even numbered topics.
produced[:,np.arange(0,100,2),:].sum ()

23468.0

In [48]:
# ODD numbered topics
produced[:,np.arange(1,100,2),:].sum ()

26532.0

In [49]:
# 7 Write a line of code that computes the number of each word produced by topic 15.
produced[:,15,:].sum (0) # or produced.sum (0)[15]

array([0., 0., 0., ..., 0., 0., 3.])

In [50]:
# 7 Write a line of code that computes the number of each word produced by topic 15.
produced.sum (0)[15]

array([0., 0., 0., ..., 0., 0., 3.])

In [51]:
# 8 Write a line of code that computes the topic responsible for the most instances of each word in the corpus.
produced.sum (0).argmax (0)

array([ 8, 74, 20, ..., 83, 35, 69], dtype=int64)

In [45]:
# 9 Write a line of code that for each topic, computes the max number of occurrences (summed over all documents) of any word that it was responsible for.
produced[:,np.arange(0,100,1),produced.sum (0).argmax (1)].sum(0) # This works, though it is possible to come up with a much better solution!

array([19., 16.,  8., 17., 20., 14., 10., 23., 13., 17., 15.,  7., 10.,
        8., 10., 16.,  7.,  9., 15., 12., 11., 23., 17., 10., 13., 13.,
       15., 14., 12., 15.,  8., 17., 12., 20., 24., 17.,  7.,  8.,  4.,
       13., 18., 17., 15.,  9., 14.,  7., 14.,  7.,  8., 15.,  7., 31.,
        9., 15.,  5., 12., 12.,  7., 10., 10., 16., 11., 13., 16., 21.,
        9.,  8.,  8.,  9., 12., 11.,  7., 18., 12., 11., 25., 13., 21.,
        9., 16., 15., 23., 21., 25.,  8., 12., 14., 12., 11., 23., 17.,
       10.,  8., 14., 12., 10., 16., 14.,  5., 12.])

In [55]:
# 9 Write a line of code that for each topic, computes the max number of occurrences (summed over all documents) of any word that it was responsible for.
produced[:,np.arange(0,100),produced.sum (0).argmax (1)].sum(0)

array([19., 16.,  8., 17., 20., 14., 10., 23., 13., 17., 15.,  7., 10.,
        8., 10., 16.,  7.,  9., 15., 12., 11., 23., 17., 10., 13., 13.,
       15., 14., 12., 15.,  8., 17., 12., 20., 24., 17.,  7.,  8.,  4.,
       13., 18., 17., 15.,  9., 14.,  7., 14.,  7.,  8., 15.,  7., 31.,
        9., 15.,  5., 12., 12.,  7., 10., 10., 16., 11., 13., 16., 21.,
        9.,  8.,  8.,  9., 12., 11.,  7., 18., 12., 11., 25., 13., 21.,
        9., 16., 15., 23., 21., 25.,  8., 12., 14., 12., 11., 23., 17.,
       10.,  8., 14., 12., 10., 16., 14.,  5., 12.])

In [5]:
# Day 1 AM Lab 4
import numpy as np
# initialize data 
import numpy as np

# this returns a number whose probability of occurence is p
def sampleValue (p):
        return np.flatnonzero (np.random.multinomial (1, p, 1))[0]

# there are 2000 words in the corpus
alpha = np.full (2000, .1)

# there are 100 topics
beta = np.full (100, .1)

# this gets us the probabilty of each word happening in each of the 100 topics
wordsInTopic = np.random.dirichlet (alpha, 100)
# wordsInCorpus[i] will give us the number of each word in the document
wordsInCorpus = {}

# generate each doc
for doc in range (0, 50):
        #
        # no words in this doc yet
        wordsInDoc = {}
        #
        # get the topic probabilities for this doc
        topicsInDoc = np.random.dirichlet (beta)
        #
        # generate each of the 1000 words in this document
        for word in range (0, 1000):
                #
                # select the topci and the word
                whichTopic = sampleValue (topicsInDoc)
                whichWord = sampleValue (wordsInTopic[whichTopic])
                #
                # and record the word
                wordsInDoc [whichWord] = wordsInDoc.get (whichWord, 0) + 1
                #
        # now, remember this document
        wordsInCorpus [doc] = wordsInDoc
print(wordsInCorpus [doc])
print(type(wordsInCorpus [doc]))

{116: 1, 25: 1, 210: 2, 1717: 3, 393: 1, 783: 1, 255: 3, 1331: 1, 285: 1, 1486: 4, 1870: 2, 566: 2, 1523: 4, 127: 2, 1176: 2, 1990: 2, 1225: 1, 1715: 2, 1056: 2, 553: 1, 1175: 2, 834: 1, 1825: 1, 1078: 1, 188: 1, 916: 2, 1804: 2, 926: 3, 800: 2, 1405: 4, 1974: 2, 1443: 2, 1616: 1, 1491: 1, 1865: 2, 649: 2, 523: 1, 1271: 2, 54: 1, 63: 4, 1409: 2, 50: 2, 604: 2, 365: 2, 667: 1, 62: 1, 555: 2, 159: 1, 1114: 1, 1552: 1, 21: 1, 245: 3, 504: 1, 1171: 2, 788: 1, 1958: 3, 753: 2, 1519: 3, 513: 1, 1460: 1, 619: 1, 1627: 1, 1734: 1, 618: 1, 1503: 1, 1385: 2, 314: 1, 719: 2, 747: 1, 1138: 1, 994: 2, 456: 1, 1600: 1, 1348: 3, 570: 1, 999: 2, 564: 2, 782: 1, 430: 1, 760: 1, 425: 1, 1966: 2, 1686: 2, 1874: 4, 1178: 4, 1553: 1, 1793: 1, 1961: 2, 738: 1, 854: 1, 438: 1, 1536: 2, 1916: 2, 1388: 3, 602: 1, 422: 2, 769: 2, 793: 2, 1585: 2, 1861: 1, 961: 2, 1068: 3, 1010: 3, 761: 3, 700: 1, 1706: 1, 857: 1, 606: 1, 235: 6, 1306: 3, 678: 1, 1336: 1, 1209: 1, 1746: 1, 1226: 1, 278: 3, 1872: 1, 119: 2, 226: 

In [7]:
# Day 1 AM Lab 4 - attempt 1 - loops through all of the documents, and then for each document, it counts the number of times that each pair of words co-occurs. Note that when you run this code, it will print out the total execution time. Hint: when you call .get (index, default) to access an entry in a dictionary, if that index in the dictionary is not occupied, the default value is returned instead. 

import time
start = time.time()
coOccurrences = {}
for doc in range (0, 50):
        for wordOne in wordsInCorpus[doc]:
                for wordTwo in wordsInCorpus[doc]:
                        coOccurrences [(wordOne, wordTwo)] = coOccurrences.get ((wordOne, wordTwo), 0) + 1
end = time.time()
end - start

12.183886051177979

In [9]:
# Next, your task is to write a similar code, this time using the NumPy array-based implementation. First, run the array-based code, which will compute the document corpus, and store it using NumPy arrays.  
import numpy as np

# there are 2000 words in the corpus
alpha = np.full (2000, .1)

# there are 100 topics
beta = np.full (100, .1)

# this gets us the probabilty of each word happening in each of the 100 topics
wordsInTopic = np.random.dirichlet (alpha, 100)

# wordsInCorpus[i] will give us the vector of words in document i
wordsInCorpus = np.zeros ((50, 2000))

# generate each doc
for doc in range (0, 50):
        #
        # get the topic probabilities for this doc
        topicsInDoc = np.random.dirichlet (beta)
        #
        # assign each of the 1000 words in this doc to a topic
        wordsToTopic = np.random.multinomial (1000, topicsInDoc)
        #
        # and generate each of the 1000 words
        for topic in range (0, 100):
                wordsFromCurrentTopic = np.random.multinomial (wordsToTopic[topic], wordsInTopic[topic])
                wordsInCorpus[doc] = np.add (wordsInCorpus[doc], wordsFromCurrentTopic)


In [10]:
# Day 1 AM Lab 4 - attempt 2 - using the NumPy array-based implementation. First, run the array-based code, which will compute the document corpus, and store it using NumPy arrays.  We will now implement the co-occurrence analysis by looping through all of the documents, taking the outer product of each document with itself, and summing. It is important when you do this that you cap any counts at one, since if wordA appears twice in a document, and wordB appears three times, the number of documents where a co-occurrence occurred is still one, not six. You can cap the value in a NumPy array using np.clip (array, minToAllow, maxToAllow)). 

import time
start = time.time()
coOccurrences = np.zeros ((2000, 2000))
for doc in range (0, 50):
        coOccurInThisDoc = np.outer (wordsInCorpus[doc], wordsInCorpus[doc])
        coOccurrences = np.add (coOccurrences, np.clip (coOccurInThisDoc, 0, 1))
end = time.time()
end - start

2.6083011627197266

In [11]:
# Day 1 AM Lab 4 - attempt 3 - one-line code that uses a matrix-multiply to compute the answer.

import time
start = time.time()
res = np.dot (np.transpose (np.clip(wordsInCorpus, 0, 1)), np.clip (wordsInCorpus, 0 , 1))
end = time.time()
end - start

0.03308558464050293

In [5]:
# day1 PM lambdas
def addTwelveToResult (myLambda):
    return myLambda (3) + 12
a = 23
aCoolLambda = lambda x : x + a
addTwelveToResult (aCoolLambda) # prints 38

38

In [6]:
a = 45
addTwelveToResult (aCoolLambda) # prints ???

60

In [7]:
import numpy as np
def sumThem (myLambda):
    tot = 0
    for a in myLambda ():
        tot = tot + a
    return tot
x = np.array([1, 2, 3, 4, 5])
iter = lambda : (j for j in x) 
sumThem (iter) # prints 15

15

In [ ]:
def countWords (fileName):
    textFile = sc.textFile (fileName)
    lines = textFile.flatMap (lambda line: line.split(" "))
    counts = lines.map (lambda word: (word, 1))
    aggCounts = counts.reduceByKey (lambda a, b: a + b)
    retrun aggCounts.top (200, key=lambda p: p[1])